#!/bin/bash
#
# chrome-logging project is a series of scripts that help collect logs of
# Google Chrome browser
#
# The MIT License (MIT)
#
# Copyright (c) 2013 Wiktor Lawski <wiktor.lawski@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

#
# Bash script ensuring collection of Google Chrome logs when issue is
# reproducible only between application restarts. There will be two log files
# available to trace the source of issue.
#
# Script prepared for Linux.
#

LOG_DIR=~/.config/google-chrome
OLD_LOG=chrome_debug.log.old
NEW_LOG=chrome_debug.log

if [ -f "$LOG_DIR/$OLD_LOG" ]
then
	: # nothing
else
	touch "$LOG_DIR/$OLD_LOG"
fi

cp "$LOG_DIR/$NEW_LOG" "$LOG_DIR/$OLD_LOG"

/usr/bin/google-chrome --enable-logging --v=1
